# This is a config for E2B sandbox template.
# You can use template ID (0gq995tmh2amkyn4qike) or template name (shipper-next-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("shipper-next-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("shipper-next-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('shipper-next-2')

team_id = "f67d591e-1ba6-4d0e-bdf5-eee81a96c53e"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "shipper-next-2"
template_id = "0gq995tmh2amkyn4qike"
