# This is a config for E2B sandbox template.
# You can use template ID (fh1a8qhpopbhvnght9o4) or template name (shipper-vite-14) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("shipper-vite-14") # Sync sandbox
# sandbox = await AsyncSandbox.create("shipper-vite-14") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('shipper-vite-14')

team_id = "54476918-f9c7-48c1-9976-8cac6ca71e41"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "shipper-vite-14"
template_id = "fh1a8qhpopbhvnght9o4"
